# Generated by Django 5.0.4 on 2024-04-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='audio',
        ),
    ]
