# Generated by Django 5.0.4 on 2024-05-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_audiodata_prompt_alter_audiodata_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='audio',
            field=models.FileField(upload_to='audios/'),
        ),
    ]
